CREATE TABLE [LOG].[INTERNAL_LOG]
(
[ERROR_NUMBER] [bigint] NULL,
[ERROR_SEVERITY] [bigint] NULL,
[ERROR_STATE] [bigint] NULL,
[ERROR_OBJECT_NAME] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ERROR_LINE] [bigint] NULL,
[ERROR_MESSAGE] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
